title: UG Event Portal
email: taricohenrt12@gmail,com
description: >-
  UG Event Portal is designed to create a centralised system that enables the student to find out events on the campus, 
  register for them and get the details about the events. Event listings can be submitted for approval, and events 
  and participation data can be handled by a dedicated dashboard available for organisers.
  
baseurl: "/CSE2201-Final-Project" 
url: "https://taricohenry.github.io"

# Build settings
theme: minima
plugins:
  - jekyll-feed